version: "3.9"
services:
  main:
    runtime: nvidia
    image: ros:melodic
    stdin_open: true
    tty: true
    command: ["bash"]
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix" 
    environment:
      DISPLAY: ${DISPLAY}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

